### ISSUE TITLE
Bad version upgrade

### ISSUE THREAD

**Issue by Cap32** [davezuko/koa-connect-history-api-fallback#4]
`v0.3.1` breaks backwards compatibility. You should use `v1.0.0` instead.

Check out `semantic-versioning` for detail:

https://docs.npmjs.com/getting-started/semantic-versioning

**Comment by davezuko** [comment]
Semantic versioning does not apply how you think it would to pre-`1.0.0` releases. In a `0` major version, a minor release can be a breaking change. That said, I didn't realize it was a breaking change, so it should have been `0.4.0`. Will revert and push two new versions.

http://semver.org/#spec-item-4

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

> Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.
